// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/singer-stack-lab/emqx-to-kafka/internal/ioc"
	"github.com/singer-stack-lab/emqx-to-kafka/internal/server"
)

// Injectors from wire.go:

func InitBridge() *server.Bridge {
	config := ioc.LoadConfig()
	client := ioc.InitSarmaClient(config)
	bridge := server.NewBridge(config, client)
	return bridge
}
